
optimistic-lock.retry:
  count: 3
  interval: 200

user-state.document: progression-service-user-state

segmentation:
  url: localhost:8080/segmentation-service/api/v1/evaluate
  connection-timeout-millis: 10000
  read-timeout-millis: 10000
  reevaluation-period-millis: 300000

configurations-cache:
  name: configurations-cache
  expiration-millis: 600000
  refresh-millis: 300000

kafka-topics:
  produced:
    rewards-topic:
      name: rewards
