
optimistic-lock.retry:
  count: 3
  interval: 200

user-state.document: progression-service-user-state

segmentation:
  url: localhost:8080/segmentation-service/api/v1/evaluate
  connection-timeout-millis: 10000
  read-timeout-millis: 10000
  refresh-period-millis: 300000